const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("trace", {
  chooseRepository: () => ipcRenderer.invoke("repository:choose"),
  openRepository: (source) => ipcRenderer.invoke("repository:open", source),
  cancelRepositoryOpen: (requestId) => ipcRenderer.invoke("repository:cancel", requestId),
  indexLimits: () => ipcRenderer.invoke("repository:limits"),
  onIndexProgress: (callback) => {
    const listener = (_event, progress) => callback(progress);
    ipcRenderer.on("repository:progress", listener);
    return () => ipcRenderer.removeListener("repository:progress", listener);
  },
  readFile: (rootPath, filePath) => ipcRenderer.invoke("repository:read-file", { rootPath, filePath }),
  detectAgents: () => ipcRenderer.invoke("agents:detect"),
  detectLanguageServers: () => ipcRenderer.invoke("index:language-servers"),
  resolveSymbol: (request) => ipcRenderer.invoke("index:resolve", request),
  graphSummary: (request) => ipcRenderer.invoke("graph:summary", request),
  graphNeighborhood: (request) => ipcRenderer.invoke("graph:neighborhood", request),
  classifyLink: (url) => ipcRenderer.invoke("links:classify", { url }),
  openLink: (url) => ipcRenderer.invoke("links:open", { url }),
  lastLinkDecision: () => ipcRenderer.invoke("links:last-decision"),
  callChains: (request) => ipcRenderer.invoke("lessons:call-chains", request),
  gradePrediction: (request) => ipcRenderer.invoke("lessons:grade-prediction", request),
  localizationExercise: (request) => ipcRenderer.invoke("exercise:localization", request),
  localizationHint: (request) => ipcRenderer.invoke("exercise:localization-hint", request),
  scoreLocalization: (request) => ipcRenderer.invoke("exercise:localization-score", request),
  raceTask: (request) => ipcRenderer.invoke("grade:race-task", request),
  gradeRace: (request) => ipcRenderer.invoke("grade:race", request),
  traceRuntimes: () => ipcRenderer.invoke("trace:runtimes"),
  runTrace: (request) => ipcRenderer.invoke("trace:run", request),
  architecture: (request) => ipcRenderer.invoke("graph:architecture", request),
  symbolFlow: (request) => ipcRenderer.invoke("graph:symbol-flow", request),
  history: (request) => ipcRenderer.invoke("history:summary", request),
  importEvidence: (request) => ipcRenderer.invoke("evidence:import", request),
  search: (request) => ipcRenderer.invoke("search:query", request),
  evaluate: (request) => ipcRenderer.invoke("eval:run", request),
  diagnose: (request) => ipcRenderer.invoke("learning:diagnose", request),
  answerProbe: (request) => ipcRenderer.invoke("learning:probe", request),
  analytics: (request) => ipcRenderer.invoke("analytics:report", request),
  nextHint: (request) => ipcRenderer.invoke("hint:next", request),
  buildActivities: (request) => ipcRenderer.invoke("activity:build", request),
  gradeActivity: (request) => ipcRenderer.invoke("activity:grade", request),
  explanationTask: (request) => ipcRenderer.invoke("explain:task", request),
  gradeExplanation: (request) => ipcRenderer.invoke("explain:grade", request),
  buildQuiz: (request) => ipcRenderer.invoke("quiz:build", request),
  gradeQuiz: (request) => ipcRenderer.invoke("quiz:grade", request),
  reviewPlan: (request) => ipcRenderer.invoke("learning:schedule", request),
  recordReview: (request) => ipcRenderer.invoke("learning:review", request),
  askAgent: (request) => ipcRenderer.invoke("agents:ask", request),
  enhanceCourse: (request) => ipcRenderer.invoke("course:enhance", request),
  loadLearning: (request) => ipcRenderer.invoke("learning:load", request),
  saveLearning: (state) => ipcRenderer.invoke("learning:save", state),
  createPractice: (request) => ipcRenderer.invoke("practice:create", request),
  inspectPractice: (sessionId) => ipcRenderer.invoke("practice:inspect", sessionId),
  openPractice: (sessionId) => ipcRenderer.invoke("practice:open", sessionId),
  removePractice: (request) => ipcRenderer.invoke("practice:remove", request),
});
